# Generated by Django 2.2.24 on 2021-06-06 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0004_recomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='writter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
